### DISCUSSION TITLE
Run commands on start workspace

### DISCUSSION THREAD

**Discussion by 201flaviosilva** [gitpod-io/openvscode-server#373] [Q&A] [answered]
Hey there ✋,

This is kinda a noob question, but when I start a workspace, the commands aren't running, they're just running when I run it for the first time, and I want every time I open the workspace to run all the commands.

My `.gitpod.yml` is currently like this:

```yml
tasks:
  - name: Install
    init: npm install
  - name: Start Server
    command: npm run server
  - name: Start Client
    command: npm run client
  - name: Start Test
    command: npm run test
```
My project: https://bitbucket.org/201flaviosilva/udemy-react-testing-library-sundaes-on-demand/

And I have other question, how do I just run all the other commands after the first one ("Install")? 

(sorry if this wasn't the right place to ask this 😅)

**Comment by jeanp413** [comment, marked as answer]
Hi @201flaviosilva you need to use `gp sync-await` and `gp sync-done`, you can read more about it [here](https://www.gitpod.io/docs/config-start-tasks#wait-for-commands-to-complete)
Right place for this questions would be our [discord server](https://discord.com/invite/gitpod)
For reporting bugs or feature requests, you can create an issue in the [Gitpod repo](https://github.com/gitpod-io/gitpod/issues)

**Reply by 201flaviosilva** [reply]
@jeanp413 Ohh, ok, make sense. Thanks for your quick response 😁

And for my other question? How do I make it run every time that I restart a workspace? (and not on start from the first time) 😅

**Reply by jeanp413** [reply]
`command` will run every time the workspace is open, I guess it was not working because you were not awaiting the `init` task, let me know if it doesn't work after using `sync-await` `sync-done`

**Reply by 201flaviosilva** [reply]
No, neither does the installation run on start

**Reply by jeanp413** [reply]
This is working:

```yaml
tasks:
  - name: Install
    init: |
      npm run install
      gp sync-done bundle
  
  - name: Start Server
    init: gp sync-await bundle
    command: npm run server

  - name: Start Client
    init: gp sync-await bundle
    command: npm run client

  - name: Start Test
    init: gp sync-await bundle
    command: npm run start:test
```
