### DISCUSSION TITLE
add repo in workspace

### DISCUSSION THREAD

**Discussion by supriyaaaic** [gitpod-io/openvscode-server#543] [Q&A]
I have a openserver vscode container running on local machine, It is exposed on localhost:3000 , i am able to clone repo from opened openserver vscode UI but i want to open a container with cloned repo by default without using UI console option

**Comment by LinuxSuRen** [comment]
I think you can add a sidecar to do it.

**Reply by mmaharjun** [reply]
what is sidecar?

**Reply by LinuxSuRen** [reply]
For instance,

```yaml
      initContainers:
        - image: {{.Spec.Image}}
          name: init
          command:
            - /bin/bash
            - -c
            - |
              set -e
              set -x
              cd /home/workspace
              git clone {{.Spec.Repository.URL}} --depth 1 --single-branch | exit 0
```
