### ISSUE TITLE
Add guidelines for setting up server with https behind proxy

### ISSUE THREAD

**Issue by bhavitsharma** [gitpod-io/openvscode-server#163]
Currently the openvscode-server serves request via http. Its implications are that some extensions like `git-graph`, `jupyter`, `markdown-enhanced-preview`, `vim` (clipboard copy/paste) don't work. I appreciate the gitpod's team concern to make minimal changes to the VSCode src so it'll be great if we can instead provide some high level guidelines on how to run openvscode with https behind some proxy (like nginx, caddy, etc). We essentially want to enable web-sockets in the reverse proxy configuration. 

Filing this FR based on [this discussion](https://github.com/gitpod-io/openvscode-server/discussions/157#discussioncomment-1495885)

**Comment by megamorf** [comment]
@akosyakov recommended Caddy. Here's my setup so you should be able to easily replicate it:

Folder structure:
```
├── caddy
│   └── Caddyfile
├── certs
│   ├── docker.localhost.crt
│   └── docker.localhost.key
├── docker-compose.yml
├── out
│   ├── DevCA.crl
│   ├── DevCA.crt
│   ├── DevCA.key
│   ├── docker.localhost.crt
│   ├── docker.localhost.csr
│   └── docker.localhost.key
├── README.md
└── workspace
``` 

Install certstrap and generate a root and web server certificate:

```
certstrap init --common-name "DevCA"
certstrap request-cert --common-name docker.localhost --domain '*.docker.localhost','localhost','*.localhost'
certstrap sign docker.localhost --CA DevCA
```

Copy the webserver cert and key to the `certs` directory: `cp ./out/docker.localhost.{crt,key} ./certs/`

***

Here are the file contents:

`./caddy/Caddyfile`

```
openvscode-server.docker.localhost

tls /certs/docker.localhost.crt /certs/docker.localhost.key

log

reverse_proxy vscode:3000
```

`docker-compose.yml`

```yaml
version: '3.7'

services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/certs:ro
      - caddy_data:/data
      - caddy_config:/config

  vscode:
    image: gitpod/openvscode-server
    restart: unless-stopped
    init: true
    expose:
      - 3000
    volumes:
      - "./workspace:/home/workspace:cached"

volumes:
  caddy_data:
  caddy_config:
```

Finally, add the CA certificate to the system's trusted CAs (Ubuntu example):

```
sudo mkdir -p /usr/local/share/ca-certificates/extra
sudo cp out/DevCA.crt /usr/local/share/ca-certificates/extra/
sudo update-ca-certificates
```

Oh and don't forget to add the hostname to your hosts file.

***

Depending on your OS/browser you might have to import the CA cert into the browser's/OS' CA certificate store and trust it for the webserver context. If you've done everything correctly you should see the trusted certificate in your browser: 

![image](https://user-images.githubusercontent.com/1732128/138362249-a42cd748-d4c3-40cd-af50-177489e62b0f.png)
![image](https://user-images.githubusercontent.com/1732128/138362289-6bef5a45-25ab-47b1-a625-9b062b716d16.png)
